### ISSUE TITLE
failed to initialize BitPay Client (Config) : failed to build configuration : Private Key not found/valid

### ISSUE THREAD

**Issue by sanaderi** [vrajroham/laravel-bitpay#22]
I'm create token by bitpay dashboard and setup other config but get this error:

failed to initialize BitPay Client (Config) : failed to build configuration : Private Key not found/valid
vendor/bitpay/sdk/src/BitPaySDK/Client.php:125

**Comment by vrajroham** [comment]
Did you add a token to .env file? Please share some steps or code, to assist you better.

**Comment by sanaderi** [comment]
Add token to last line of laravel-bitpay.php config file like the attached file

![Screenshot_20200907-200836_JuiceSSH](https://user-images.githubusercontent.com/11719622/92403968-c945fa80-f147-11ea-92a1-45a59d936d92.jpg)

**Comment by asadglobalshopaholics** [comment]
@vrajroham same issue i'm facing right now what i observe that when i run **php artisan laravel-bitpay:createkeypair** this will create **bitpay.pri**  file in **/tmp** directory using OS ubuntu but i'm unable to find **bitpay.pub** file in /tmp directory may be this issue i'm facing due to this reason can you please help that how can i get bitpay.pub file or there is another way to create it ???

**Comment by vrajroham** [comment]
@asadglobalshopaholics Change your key location to project storage where those keys could be persistently stored.

E.g.
```dotenv
BITPAY_PRIVATE_KEY_PATH=/var/www/project-name/storage/bitpay.pri
BITPAY_PUBLIC_KEY_PATH=/var/www/project-name/storage/tmp/bitpay.pub
```

This should help

**Comment by brijesh1997** [comment]
@vrajroham , I am fetching issue same as @asadglobalshopaholics 

I tried above your given solution but I didn't find bitpay.pub file.
